# 4.1 Numpy ndarray: 다차원 배열 객체

In [1]:
import numpy as np
data = np.random.randn(2,3)
data

array([[ 1.00472984,  0.53864043,  0.88561534],
       [-0.09844167, -1.45869639, -0.08099963]])

## 4.1.1 ndarray 생성

In [2]:
data1=[6, 7.5, 8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [3]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.empty((2,3,2))

array([[[1.29664881e-316, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 3.21142670e-322]],

       [[6.91228963e-310, 1.42465133e-316],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [7]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## 4.1.2 ndarray의 자료형

In [9]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr1.dtype

dtype('float64')

## 4.1.3 배열과 스칼라 간의 연산

## 4.1.5 불리언 색인

bob이 아닌 요소 선택시, != 연산자, -로 조건절 부정하기

## 4.1.6 팬시 색인

In [10]:
arr = np.empty((8,4))

for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [11]:
arr[[4,3,0,6]] # 특정한 순서로 행을 선택하고 싶은 경우

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [12]:
arr[[-3,-5,-7]] # 색인을 음수로 사용 -> 끝에서부터 행을 선택

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [13]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])