# 5.1 pandas 자료 구조 소개

In [1]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

## 5.1.1 Series

In [2]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values # Series의 배열 얻기

array([ 4,  7, -5,  3])

In [4]:
obj.index # Series의 인덱스 얻기

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [7]:
obj2['a']

-5

In [8]:
obj2['d']=6

In [9]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [10]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [11]:
'b' in obj2

True

In [12]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}
obj3 = Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [13]:
states = ['California', 'Ohio', 'Oregeon', 'Texas']
obj4 = Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregeon           NaN
Texas         71000.0
dtype: float64

In [14]:
pd.isnull(obj4)

California     True
Ohio          False
Oregeon        True
Texas         False
dtype: bool

In [15]:
pd.notnull(obj4)

California    False
Ohio           True
Oregeon       False
Texas          True
dtype: bool

In [16]:
obj4.isnull()

California     True
Ohio          False
Oregeon        True
Texas         False
dtype: bool

In [17]:
obj4.name = 'popilation'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregeon           NaN
Texas         71000.0
Name: popilation, dtype: float64

In [18]:
obj.index = ['Bob', 'Steve', 'Jeff','Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## 5.1.2 DataFrame

In [19]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
       'year':[2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [20]:
pd.DataFrame(data, columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [21]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                     index=['one','two','three','four','five'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [22]:
frame2['debt']=16.5

In [23]:
val = Series([-1.2, 1.5, -1.7], index=['two','four','five'])
frame2['debt']=val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   1.5
five   2002  Nevada  2.9  -1.7

In [24]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4   1.5    False
five   2002  Nevada  2.9  -1.7    False

In [25]:
del frame2['eastern'] # del로 열 삭제하기

frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4   1.5
five   2002  Nevada  2.9  -1.7

In [26]:
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

frame3=pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [27]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [28]:
pd.DataFrame(pop, index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [29]:
pdata={'Ohio':frame3['Ohio'][:-1],
      'Nevada':frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [30]:
frame3.index.name = 'year';frame3.columns.name='state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [31]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [32]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, 1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

## 5.1.3 색인객체

In [33]:
obj = Series(range(3), index=['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [34]:
obj2 = Series([1.5,-2.5,0], index=index)
obj2.index is index

True

# 5.2 핵심 기능

## 5.2.1 재색인

In [35]:
obj = Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [36]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [37]:
obj.reindex(['a','b','c','d','e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [38]:
obj3 = Series(['blue','purple', 'yellow'], index=[0,2,4])
obj3.reindex(range(6), method='ffill') # ffill 앞의 값으로 누락값 채우기

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [39]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)), index=['a','c','d'],
                    columns=['Ohio','Texas','California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [40]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [41]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

## 5.2.2 하나의 로우 또는 컬럼 삭제하기

In [42]:
obj = Series(np.arange(5.), index=['a','b','c','d','e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [43]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [44]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                           index=['Ohio','Colorado','Utah','New York'],
                           columns = ['one','two','three','four'])
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [45]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## 5.2.3 색인하기, 선택하기, 거르기

In [46]:
obj = Series(np.arange(4.),index=['a','b','c','d'])
obj['b']

1.0

In [47]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [48]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),
                           index=['Ohio','Colorado','Utah','New York'],
                           columns = ['one','two','three','four'])
data[['three','four']]

three  four
Ohio          2     3
Colorado      6     7
Utah         10    11
New York     14    15

In [49]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [50]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

## 5.2.4 산술연산과 데이터 정렬

In [51]:
s1 = Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a','c','e','f','g'])

In [52]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

## DataFrame과 Series 간의 연산

## 5.2.5 함수 적용과 매핑

In [53]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    1.194816 -0.560993  1.038791
Ohio    0.075786 -0.870016  1.024204
Texas   1.634435  0.086277 -0.041595
Oregon -0.772791 -1.422698  0.209853

In [54]:
f = lambda x:x.max()-x.min()

frame.apply(f)

b    2.407226
d    1.508975
e    1.080386
dtype: float64

In [55]:
frame.apply(f, axis=1)

Utah      1.755809
Ohio      1.894220
Texas     1.676030
Oregon    1.632552
dtype: float64

In [56]:
def f(x):
    return Series([x.min(), x.max()], index=['min','max'])

frame.apply(f)

b         d         e
min -0.772791 -1.422698 -0.041595
max  1.634435  0.086277  1.038791

In [57]:
format = lambda x: '%.2f'%x
frame.applymap(format)

b      d      e
Utah     1.19  -0.56   1.04
Ohio     0.08  -0.87   1.02
Texas    1.63   0.09  -0.04
Oregon  -0.77  -1.42   0.21

## 5.2.6 정렬과 순위

In [58]:
obj = Series(range(4), index=['d','a','b','c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [59]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)), index=['three', 'one'],
                  columns=['d','a','b','c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [60]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [61]:
obj = Series([4,7,-3,2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

## 5.2.7 중복 색인

In [62]:
obj = Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [63]:
obj.index.is_unique

False

In [64]:
df = pd.DataFrame(np.random.randn(4,3), index=['a','a','b','b'])
df

0         1         2
a  0.008229 -1.211459 -0.609382
a -1.006986 -0.778327 -0.658785
b  2.503741 -0.783374  0.430464
b -2.349198  1.039090  0.011324

# 5.5 계층적 색인

In [65]:
frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                              index=[['a','a','b','b'],[1,2,1,2]],
                              columns=[['Ohio','Ohio','Colorado'],
                                      ['Green','Red','Green']])
frame

Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [66]:
frame.index.names=['key1','key2']
frame.columns.names=['state','color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2                   
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [67]:
frame['Ohio']

color      Green  Red
key1 key2            
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

## 5.5.1 계층 순서 바꾸고 정렬하기

In [68]:
frame.swaplevel('key1','key2') # 받은 2개의 계층 번호, 이름을 뒤바꿔서 반환하기

state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [70]:
frame.sort_index(1)

/tmp/ipykernel_1126459/2812708312.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  frame.sort_index(1)


state     Colorado  Ohio    
color        Green Green Red
key1 key2                   
a    1           2     0   1
     2           5     3   4
b    1           8     6   7
     2          11     9  10

In [73]:
frame.swaplevel(0,1).sort_index(0)

/tmp/ipykernel_1126459/2854367505.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.sort_index will be keyword-only.
  frame.swaplevel(0,1).sort_index(0)


state      Ohio     Colorado
color     Green Red    Green
key2 key1                   
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

## 5.5.2 단위별 요약 통계

In [74]:
frame.sum(level='key2')

/tmp/ipykernel_1126459/2004046222.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  frame.sum(level='key2')


state  Ohio     Colorado
color Green Red    Green
key2                    
1         6   8       10
2        12  14       16

In [75]:
frame.sum(level='color', axis=1)

/tmp/ipykernel_1126459/4133796543.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  frame.sum(level='color', axis=1)


color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

## 5.5.3 Dataframe의 컬럼 이용하기

In [76]:
frame = pd.DataFrame({'a':range(7), 'b':range(7,0,-1),
                     'c':['one','one','one','two','two','two','two'],
                     'd':[0,1,2,0,1,2,3]})
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [77]:
frame2 = frame.set_index(['c','d'])
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [78]:
frame.set_index(['c','d'], drop=False)

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [79]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

# 데이터사이언스 스쿨
## 4장 판다스 데이터분석
### 4.5 데이터프레임 인덱스 조작

In [2]:
import numpy as np
import pandas as pd

np.random.seed(0)
df4 = pd.DataFrame(np.round(np.random.randn(6, 4), 2),
                   columns=[["A", "A", "B", "B"],
                            ["C", "D", "C", "D"]],
                   index=[["M", "M", "M", "F", "F", "F"],
                          ["id_" + str(i + 1) for i in range(3)] * 2])
df4.columns.names = ["Cidx1", "Cidx2"]
df4.index.names = ["Ridx1", "Ridx2"]
df4

Cidx1           A           B      
Cidx2           C     D     C     D
Ridx1 Ridx2                        
M     id_1   1.76  0.40  0.98  2.24
      id_2   1.87 -0.98  0.95 -0.15
      id_3  -0.10  0.41  0.14  1.45
F     id_1   0.76  0.12  0.44  0.33
      id_2   1.49 -0.21  0.31 -0.85
      id_3  -2.55  0.65  0.86 -0.74

In [4]:
df4.stack("Cidx1") # 열 인덱스 -> 행 인덱스로 변환
df4.stack(1) # 인덱스를 지정할 때는 문자열 이름과 순서를 표시하는 숫자 인덱스를 모두 사용

Cidx1                 A     B
Ridx1 Ridx2 Cidx2            
M     id_1  C      1.76  0.98
            D      0.40  2.24
      id_2  C      1.87  0.95
            D     -0.98 -0.15
      id_3  C     -0.10  0.14
            D      0.41  1.45
F     id_1  C      0.76  0.44
            D      0.12  0.33
      id_2  C      1.49  0.31
            D     -0.21 -0.85
      id_3  C     -2.55  0.86
            D      0.65 -0.74